Fix typos
drwl/annotaterb pull request #165
Opened 2024-11-24 15:26 UTC by tagliala

No changes to production code

Found with `codespell`

2025-01-22 06:56 UTC, drwl requested changes
just 1 change, otherwise thank you for running it

2025-01-22 06:56 UTC, drwl commented on CHANGELOG.md
> +- Update dummy app dependencies [\#17](https://github.com/drwl/annotaterb/pull/17) ([drwl](https://github.com/drwl))
This is auto generated by a changelog script, could you remove this? I'll see if fixing the issue name upstream will solve this issue going forward.

2025-01-22 09:07 UTC, tagliala commented
Comment addressed and rebased.

Failures depend on a change related to concurrent ruby which is not requiring logger anymore.

This should be fixed in Rails >= 7.1. Rails 7.0 is in EOL and will not be fixed

2025-01-23 17:32 UTC, drwl approved these changes

2025-01-23 17:32 UTC, drwl commented
> Comment addressed and rebased.
> 
> Failures depend on a change related to concurrent ruby which is not requiring logger anymore.
> 
> This should be fixed in Rails >= 7.1. Rails 7.0 is in EOL and will not be fixed

Thank you! It seems like I'll have to do some work with the testing harness to fix CI.

2025-01-23 17:32 UTC, merged

2025-01-25 12:55 UTC, tagliala commented
Welcome

>  I'll have to do some work with the testing harness to fix CI.

In the meanwhile, you can merge #180 to have a green build